In [1]:
import fastf1
import pandas as pd

In [5]:
fastf1.Cache.enable_cache("../data/cache")

In [6]:
session = fastf1.get_session(2023, "Bahrain", "R")
session.load()

core           INFO 	Loading data for Bahrain Grand Prix - Race [v3.8.3]
req            INFO 	No cached data found for session_info. Loading data...
_api           INFO 	Fetching session info data...
req            INFO 	Data has been written to cache!
req            INFO 	No cached data found for driver_info. Loading data...
_api           INFO 	Fetching driver list...
req            INFO 	Data has been written to cache!
req            INFO 	No cached data found for session_status_data. Loading data...
_api           INFO 	Fetching session status data...
req            INFO 	Data has been written to cache!
req            INFO 	No cached data found for lap_count. Loading data...
_api           INFO 	Fetching lap count data...
req            INFO 	Data has been written to cache!
req            INFO 	No cached data found for track_status_data. Loading data...
_api           INFO 	Fetching track status data...
req            INFO 	Data has been written to cache!
req            INFO 	No cached data found for _extended_timing_data. Loading data...
_api           INFO 	Fetching timing data...
_api           INFO 	Parsing timing data...
req            INFO 	Data has been written to cache!
req            INFO 	No cached data found for timing_app_data. Loading data...
_api           INFO 	Fetching timing app data...
req            INFO 	Data has been written to cache!
core           INFO 	Processing timing data...
req            INFO 	No cached data found for car_data. Loading data...
_api           INFO 	Fetching car data...
_api           INFO 	Parsing car data...
req            INFO 	Data has been written to cache!
req            INFO 	No cached data found for position_data. Loading data...
_api           INFO 	Fetching position data...
_api           INFO 	Parsing position data...
req            INFO 	Data has been written to cache!
req            INFO 	No cached data found for weather_data. Loading data...
_api           INFO 	Fetching weather data...
req            INFO 	Data has been written to cache!
req            INFO 	No cached data found for race_control_messages. Loading data...
_api           INFO 	Fetching race control messages...
req            INFO 	Data has been written to cache!
core           INFO 	Finished loading data for 20 drivers: ['1', '11', '14', '55', '44', '18', '63', '77', '10', '23', '22', '2', '20', '21', '27', '24', '4', '31', '16', '81']

In [7]:
results = session.results
results.head()

,DriverNumber,BroadcastName,Abbreviation,DriverId,TeamName,TeamColor,TeamId,FirstName,LastName,FullName,...,Position,ClassifiedPosition,GridPosition,Q1,Q2,Q3,Time,Status,Points,Laps
1,1,M VERSTAPPEN,VER,max_verstappen,Red Bull Racing,3671C6,red_bull,Max,Verstappen,Max Verstappen,...,1.0,1,1.0,NaT,NaT,NaT,0 days 01:33:56.736000,Finished,25.0,57.0
11,11,S PEREZ,PER,perez,Red Bull Racing,3671C6,red_bull,Sergio,Perez,Sergio Perez,...,2.0,2,2.0,NaT,NaT,NaT,0 days 00:00:11.987000,Finished,18.0,57.0
14,14,F ALONSO,ALO,alonso,Aston Martin,358C75,aston_martin,Fernando,Alonso,Fernando Alonso,...,3.0,3,5.0,NaT,NaT,NaT,0 days 00:00:38.637000,Finished,15.0,57.0
55,55,C SAINZ,SAI,sainz,Ferrari,F91536,ferrari,Carlos,Sainz,Carlos Sainz,...,4.0,4,4.0,NaT,NaT,NaT,0 days 00:00:48.052000,Finished,12.0,57.0
44,44,L HAMILTON,HAM,hamilton,Mercedes,6CD3BF,mercedes,Lewis,Hamilton,Lewis Hamilton,...,5.0,5,7.0,NaT,NaT,NaT,0 days 00:00:50.977000,Finished,10.0,57.0

In [ ]:
results[[
    "Abbreviation", 
    "FullName", 
    "TeamName", 
    "GridPosition", 
    "Position", 
    "Status"
    ]]
# grid position pretty vital info ngl

,Abbreviation,FullName,TeamName,GridPosition,Position,Status
1,VER,Max Verstappen,Red Bull Racing,1.0,1.0,Finished
11,PER,Sergio Perez,Red Bull Racing,2.0,2.0,Finished
14,ALO,Fernando Alonso,Aston Martin,5.0,3.0,Finished
55,SAI,Carlos Sainz,Ferrari,4.0,4.0,Finished
44,HAM,Lewis Hamilton,Mercedes,7.0,5.0,Finished
18,STR,Lance Stroll,Aston Martin,8.0,6.0,Finished
63,RUS,George Russell,Mercedes,6.0,7.0,Finished
77,BOT,Valtteri Bottas,Alfa Romeo,12.0,8.0,Finished
10,GAS,Pierre Gasly,Alpine,20.0,9.0,Finished
23,ALB,Alexander Albon,Williams,15.0,10.0,Finished
22,TSU,Yuki Tsunoda,AlphaTauri,14.0,11.0,Finished
2,SAR,Logan Sargeant,Williams,16.0,12.0,Lapped
20,MAG,Kevin Magnussen,Haas F1 Team,17.0,13.0,Lapped
21,DEV,Nyck De Vries,AlphaTauri,19.0,14.0,Lapped
27,HUL,Nico Hulkenberg,Haas F1 Team,10.0,15.0,Lapped
24,ZHO,Guanyu Zhou,Alfa Romeo,13.0,16.0,Lapped
4,NOR,Lando Norris,McLaren,11.0,17.0,Lapped
31,OCO,Esteban Ocon,Alpine,9.0,18.0,Retired
16,LEC,Charles Leclerc,Ferrari,3.0,19.0,Retired
81,PIA,Oscar Piastri,McLaren,18.0,20.0,Retired

In [ ]:
results.columns  # Just gives column names, not the data itself

Index(['DriverNumber', 'BroadcastName', 'Abbreviation', 'DriverId', 'TeamName',
       'TeamColor', 'TeamId', 'FirstName', 'LastName', 'FullName',
       'HeadshotUrl', 'CountryCode', 'Position', 'ClassifiedPosition',
       'GridPosition', 'Q1', 'Q2', 'Q3', 'Time', 'Status', 'Points', 'Laps'],
      dtype='object')

In [13]:
# first mini insight
results[["FullName", "TeamName", "GridPosition", "Position"]].sort_values(by="GridPosition") 
# grid position is the starting position
# position is just the finishing one

           FullName         TeamName  GridPosition  Position
1    Max Verstappen  Red Bull Racing           1.0       1.0
11     Sergio Perez  Red Bull Racing           2.0       2.0
16  Charles Leclerc          Ferrari           3.0      19.0
55     Carlos Sainz          Ferrari           4.0       4.0
14  Fernando Alonso     Aston Martin           5.0       3.0
63   George Russell         Mercedes           6.0       7.0
44   Lewis Hamilton         Mercedes           7.0       5.0
18     Lance Stroll     Aston Martin           8.0       6.0
31     Esteban Ocon           Alpine           9.0      18.0
27  Nico Hulkenberg     Haas F1 Team          10.0      15.0
4      Lando Norris          McLaren          11.0      17.0
77  Valtteri Bottas       Alfa Romeo          12.0       8.0
24      Guanyu Zhou       Alfa Romeo          13.0      16.0
22     Yuki Tsunoda       AlphaTauri          14.0      11.0
23  Alexander Albon         Williams          15.0      10.0
2    Logan Sargeant         Williams          16.0      12.0
20  Kevin Magnussen     Haas F1 Team          17.0      13.0
81    Oscar Piastri          McLaren          18.0      20.0
21    Nyck De Vries       AlphaTauri          19.0      14.0
10     Pierre Gasly           Alpine          20.0       9.0